### ISSUE TITLE
Sapphire Rapids FSP

### ISSUE THREAD

**Issue by pp3345** [intel/FSP#95]
Does Intel plan to release a coreboot-compatible FSP for Sapphire Rapids CPUs / Eagle Stream platform, and if so, is there an estimate available on when the FSP will be published?

**Comment by 65a** [comment]
Hoping Intel wants to sell more chips and responds! Seeing the public contributions to coreboot from Intel and ODMs for SPR-SP is great, but none of it is usable months later, because it is not possible to get the FSP binaries that were used. I have a COTS board that could probably be added to the tree today if I could actually build coreboot with the necessary FSP blobs.

**Comment by LeanSheng** [comment]
hi guys, quick update: the SPR (Sapphire Rapids) FSP is here :D
https://github.com/intel/FSP/tree/master/EagleStreamFspBinPkg
Feel free to reach me out if need any help on integrating them for coreboot usage ;)
sheng.tan@9elements.com

**Comment by nate-desimone** [comment]
Fixed in 848c499
